- name: tarea posinstalacion 1 # Copiar la configuracion de nginx
  template:
    src: templates/minginx.conf
    dest: /etc/nginx/conf.d/minginx.conf
    mode: '0400'
  notify: nginx_reconfigurado
  
- name: tarea posinstalacion 2 # Clonar el web
  git:
    repo: 'https://jalvarso2323:{{password_github}}@github.com/jalvarso2323/Proyecto_Nginx.git'
    dest: '{{ nginx_web_path }}'
    